FROM ubuntu:18.04

RUN export DEBIAN_FRONTEND=noninteractive &&\
    apt-get update &&\
    apt-get install\
    -y php7.2 composer\
    php-mysql\
    php-mbstring\
    apache2\
    php7.2-xml

COPY composer.lock composer.json config.php main.php patterns routes.php /var/www/html/
COPY src /var/www/html/src
WORKDIR /var/www/html
COPY configs-for-docker/backend/php.ini /etc/php/7.2/apache2/
COPY configs-for-docker/backend/000-default.conf /etc/apache2/sites-available/

RUN composer install --no-dev &&\
    a2enmod rewrite &&\
    touch log &&\
    chmod 777 log

EXPOSE 80

ENTRYPOINT service apache2 start &&\
           /bin/bash