FROM ubuntu:18.04

RUN export DEBIAN_FRONTEND=noninteractive &&\
    apt-get update &&\
    apt-get install -y apache2

COPY ./frontend /var/www/html/frontend/
WORKDIR /var/www/html

COPY configs-for-docker/frontend/000-default.conf /etc/apache2/sites-available/
COPY configs-for-docker/frontend/apache2.conf /etc/apache2/

RUN a2enmod rewrite && sed -i 's/172.17.0.1:80/172.17.0.3:80/g' frontend/static/main.js

EXPOSE 80

ENTRYPOINT service apache2 start &&\
           /bin/bash